import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { ToolDefinition } from "./types.js";
import { failedObservation, observation } from "./types.js";
import { callFinanceEngine } from "./pythonBridge.js";

export interface BacktestInput {
  symbol: string;
  strategy?: string;
  start?: string;
  end?: string;
  initialCapital?: number;
}

export interface BacktestResult {
  symbol: string;
  strategy: string;
  start: string;
  end: string;
  data?: {
    provider: string;
    points: number;
    firstPrice: number;
    lastPrice: number;
  };
  assumptions: {
    initialCapital?: number;
    feesBps: number;
    slippageBps: number;
    liveTrading: false;
  };
  metrics: {
    finalEquity?: number;
    totalReturnPct: number;
    maxDrawdownPct: number;
    trades: number;
  };
  validation?: {
    passed: boolean;
    checks: Record<string, boolean>;
  };
  warnings?: string[];
  artifactPath: string;
  reportPath?: string;
}

export interface ResearchWorkflowResult {
  backtest: BacktestResult;
  reportMarkdown: string;
}

export function normalizeSymbol(symbol: string): string {
  return symbol.trim().toUpperCase().replace(/[^A-Z0-9._-]/g, "");
}

async function persistWorkflowArtifacts(workspace: string, result: ResearchWorkflowResult): Promise<BacktestResult> {
  const backtest = result.backtest;
  const symbol = normalizeSymbol(backtest.symbol);
  const strategy = backtest.strategy;
  const artifactDir = join(workspace, "artifacts", symbol, "backtests");
  const reportDir = join(workspace, "reports", symbol);
  await mkdir(artifactDir, { recursive: true });
  await mkdir(reportDir, { recursive: true });
  const artifactPath = join(artifactDir, `${strategy}.json`);
  const reportPath = join(reportDir, `${strategy}.md`);
  const persisted = { ...backtest, artifactPath, reportPath };
  await writeFile(artifactPath, `${JSON.stringify(persisted, null, 2)}\n`, "utf8");
  await writeFile(reportPath, `${result.reportMarkdown}\n`, "utf8");
  return persisted;
}

export function researchWorkflowTool(): ToolDefinition<BacktestInput, BacktestResult> {
  return {
    name: "run_research_workflow",
    description: "Run a deterministic local research workflow: deterministic local data, trend strategy backtest, validation checks, artifact persistence, and Markdown report generation.",
    category: "backtest",
    schema: {
      type: "object",
      required: ["symbol"],
      properties: {
        symbol: { type: "string", description: "Ticker symbol, for example SPY" },
        strategy: { type: "string", description: "Strategy name" },
        start: { type: "string", description: "Start date YYYY-MM-DD" },
        end: { type: "string", description: "End date YYYY-MM-DD" },
        initialCapital: { type: "number", description: "Initial paper capital" },
      },
      additionalProperties: false,
    },
    async execute(input, context) {
      const symbol = normalizeSymbol(input.symbol ?? "");
      if (!symbol) return failedObservation("run_research_workflow", "symbol is required") as never;
      const params = {
        symbol,
        strategy: input.strategy ?? "moving-average-trend-baseline",
        start: input.start ?? "2020-01-01",
        end: input.end ?? "2024-12-31",
        initialCapital: input.initialCapital ?? 10_000,
      };
      const response = await callFinanceEngine<ResearchWorkflowResult>({ method: "run_research_workflow", params });
      if (!response.data) return failedObservation("run_research_workflow", "finance engine returned no data") as never;
      const persisted = await persistWorkflowArtifacts(context.workspace, response.data);
      return observation("run_research_workflow", persisted, {
        provenance: {
          ...(response.metadata ?? {}),
          artifactPath: persisted.artifactPath,
          reportPath: persisted.reportPath,
        },
        warnings: persisted.warnings ?? ["Research and paper validation only."],
      });
    },
  };
}

export function localBacktestTool(): ToolDefinition<BacktestInput, BacktestResult> {
  return {
    ...researchWorkflowTool(),
    name: "run_local_backtest",
    description: "Compatibility alias for the deterministic local research workflow backtest tool.",
  };
}

export function reportTool(): ToolDefinition<{ title?: string; backtest: BacktestResult }, { path: string; markdown: string }> {
  return {
    name: "generate_report",
    description: "Generate a Markdown research report from a tool-backed backtest result.",
    category: "report",
    schema: { type: "object" },
    async execute(input, context) {
      const bt = input.backtest;
      if (bt.reportPath) {
        return observation("generate_report", { path: bt.reportPath, markdown: "Report already generated by research workflow." }, { provenance: { source: bt.artifactPath } });
      }
      const title = input.title ?? `${bt.symbol} ${bt.strategy} research report`;
      const markdown = [
        `# ${title}`,
        "",
        "Research and paper validation only. No live trading or profit guarantees.",
        "",
        `- Symbol: ${bt.symbol}`,
        `- Strategy: ${bt.strategy}`,
        `- Period: ${bt.start} to ${bt.end}`,
        `- Fees: ${bt.assumptions.feesBps} bps`,
        `- Slippage: ${bt.assumptions.slippageBps} bps`,
        `- Total return: ${bt.metrics.totalReturnPct}%`,
        `- Max drawdown: ${bt.metrics.maxDrawdownPct}%`,
        `- Trades: ${bt.metrics.trades}`,
        "",
        "Limitations: deterministic local scaffold engine; replace with audited historical data before relying on results.",
      ].join("\n");
      const dir = join(context.workspace, "reports", bt.symbol);
      await mkdir(dir, { recursive: true });
      const path = join(dir, `${bt.strategy}.md`);
      await writeFile(path, `${markdown}\n`, "utf8");
      return observation("generate_report", { path, markdown }, { provenance: { source: bt.artifactPath } });
    },
  };
}
